language: node_js
node_js:
  - "11"
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - ng build --base-href /pcws-viewer/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/pcws-viewer
  on:
    branch: master
